# Generated by Django 3.0.11 on 2020-12-18 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=70)),
                ('DNI', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')], verbose_name='Numero del celular personal')),
                ('telefono', models.CharField(blank=True, max_length=7, verbose_name='Numero telefonico del hogar')),
                ('email', models.EmailField(error_messages={'unique': 'Ya hay un usuario asociado a este correo.'}, max_length=254, unique=True, verbose_name='Direccions de correo electronico')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('COMPROMETIDO', 'Comprometido'), ('AVENTURERO', 'Aventutero')], max_length=12)),
            ],
        ),
    ]
