# Generated by Django 3.0.11 on 2020-12-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'ordering': ('username',)},
        ),
    ]
