# Generated by Django 3.0.11 on 2020-12-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20201223_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='personas',
            name='estado_civil',
        ),
        migrations.AddField(
            model_name='personas',
            name='estado_civil',
            field=models.ManyToManyField(to='personas.EstadoCivil'),
        ),
    ]
